version: '3.9'
services:
  backend:
    image: mostafamedhat1/e-commerce-platform_backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - frontend
      - backend
    depends_on:
      db:
        condition: service_healthy

  frontend:
    image: mostafamedhat1/e-commerce-platform_frontend
    restart: unless-stopped
    ports:
      - "5174:5174"
    depends_on:
      - backend
    networks:
      - frontend    

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: my_database
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      backend:
        aliases:
          - mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  mysql_data:

networks:
  frontend:
  backend:
